Repository zestframework/Zest_Framework, pull requests merged in 2019-03, with the labels that each got.

#167 Proposal fix for #166
  src/Component/Component.php
Labels: Proposal

#171 fix for #168
  src/http/Headers.php
Labels: Proposal

#178 New proposal to get server/document root
  src/Common/Root.php
Labels: Proposal

#199 Create Arrays package
  Tests/Data/ArraysTest.php
  src/Contracts/Data/Arrays.php
  src/Data/Arrays.php
Labels: Feature Request, Proposal, enhancement

#208 General cleanup + improve some comments.
  src/Files/Files.php
  src/Language/Language.php
  src/Language/LanguageCodesTrait.php
  src/Mail/Mail.php
Labels: enhancement

#210 Resolves issue #209
  composer.json
Labels: enhancement

#213 Update SodiumEncryption.php
  src/Encryption/Adapter/SodiumEncryption.php
Labels: bug
