Repository zestframework/Zest_Framework, pull requests merged in 2019-10, with the labels that each got.

#259 Fix Array class behavior and tests
  Tests/Data/ArraysTest.php
  src/Data/Arrays.php
Labels: enhancement

#260 Enchantment of str class #247 - Adds hasUpercase and hasLowercase function with tests
  Tests/Data/StrTest.php
  src/Data/Str.php
Labels: enhancement, hacktoberfest

#269 Member ttl has private access
  src/Cache/Adapter/APC.php
  src/Cache/Adapter/APCU.php
  src/Cache/Adapter/FileCache.php
  src/Cache/Adapter/Memcache.php
  src/Cache/Adapter/Memcached.php
  src/Cache/Adapter/Redis.php
  src/Cache/Adapter/SessionCache.php
Labels: bug, enhancement, hacktoberfest

#268 Bugfix: many variable names are not there
  src/Cache/Adapter/Redis.php
  src/Cache/Cache.php
  src/Common/FTP.php
  src/Common/Formats.php
  src/Container/Container.php
  src/Files/Files.php
  src/Input/Input.php
  src/Mail/Mail.php
  src/Router/Router.php
  src/Session/Session.php
  src/http/Uri.php
Labels: enhancement, hacktoberfest

#267 Adds convert case method in str class and adds tests
  Tests/Data/StrTest.php
  src/Data/Str.php
Labels: enhancement, hacktoberfest

#272 Add isBase64 and substring methods to Str class
  Tests/Data/StrTest.php
  src/Data/Str.php
Labels: enhancement, good first issue, hacktoberfest

#279 Add String methods
  Tests/Data/StrTest.php
  src/Data/Str.php
Labels: enhancement, good first issue, hacktoberfest

#280 Fix behaviour of hasUppercase and hasLowercase
  Tests/Data/StrTest.php
  src/Data/Str.php
Labels: bug, enhancement, hacktoberfest

#281 feat: add the option to output assoc arrays fixes #261
  Tests/Data/ArraysTest.php
  src/Contracts/Data/Arrays.php
  src/Data/Arrays.php
Labels: enhancement, good first issue, hacktoberfest

#285 Fix for #282
  .travis.yml
Labels: enhancement, hacktoberfest

#284 Create PasswordManipulationTest.php
  Tests/Common/PasswordManipulationTest.php
  changes.md
  src/Common/PasswordManipulation.php
  src/Site/Site.php
  src/functions/helpers.php
Labels: enhancement, hacktoberfest

#296 Changes the interface statment to use
  src/Site/Key.php
Labels: bug, hacktoberfest

#297 Update Bootstrap.php
  src/Bootstrap.php
Labels: enhancement, hacktoberfest

#298 Update FileInfo.php
  src/Files/FileInfo.php
Labels: enhancement, hacktoberfest

#308 Fix some typos + general cleanup.
  .travis.yml
  PULL_REQUEST_TEMPLATE.md
  phpunit.xml
  readme.md
  src/Auth/Logout.php
  src/Console/Console.php
  src/Database/Drives/MYSQL/MySqlDb.php
  src/Database/Drives/SqLite/SqLite.php
  src/Site/Key.php
  src/Whoops/views/view.php
  src/http/Clients/AbstractClient.php
Labels: enhancement, hacktoberfest

#294 Feature/add testclass container
  Tests/Container/ContainerTest.php
  src/Container/Container.php
Labels: enhancement, hacktoberfest
